language: go
go:
- tip
install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
script: COVERALLS="-service travis-ci -repotoken $COVERALLS_TOKEN" ./test-coverage.sh
COVERALLS_TOKEN:
  secure: Z4K1CjU5kIXAHParqV8EpAFwYM0vNSD9Cq5EcrIiJm3mz4OzTlPD9RWAn3azN2jj5jQ5FF2GvoHouaLWlUm9SgNTiFNFA3jiHpLBD8WCZaPKvMc89HjwvfRutSK8ZnwiXj63Rx5IPaTRjm/CtI6mgyXB5CmGHNHbvEC+ZPMRf/BUwJmCwMsELZIAFKjP9nqkTqh/vWxEPwhseMCZfCMl2bnGdVlQP0/epMo3yQ26Nu5BlH0v9DQegstDJ1NxTAFadW8BwEFHZNyy+CSxR5H9LBNqmXAl2z1KXNKKjBcaCcNBPrWsTCwdfsRM/VR9efcm03OyOsSb5jG2QfPRMkaCi4h2QQnWHv/WC1MD5uUpPAIiE/K1ppnmUmXOKgY1ZEghbeHeqlyo1FcRKx8OTR4rcn704pBYc5my8nemrIk1QjCvFa+/YWDs43sBUHmBESYAvQZoKTxWpg9Gk/4baog2cd0QrbxkSL9qZLoo+UZjbAJxnHOC7jKnS+zhPIiBjRO7BHDSp6nW0tZivsave/JWc1XPYQ+dQRzQqr6+JxcQMCaoBJr3ulk37VdOrSyrYqtqBFA1aBH3jybPh6r+y5/3pWMAot+a7K1r/4q1bx75gr76yzOU7onpLO+53bzrwMSVHm7FPAa8an3PQOHGULIpycjwah0T/i8wU42aKE5ctaI=
