language: go
go:
- 1.3
- 1.4
- 1.5
- 1.6
- tip
install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
script: COVERALLS="-service travis-ci -repotoken $COVERALLS_TOKEN" ./test-coverage.sh
env:
  - secure: "AvhJazERbu5j3LuhtOvit/sJI/460KFxjMMyGzR2UQdoiuwWtDz2PKc5szb8moCmbXsL0/KyPgdB5Ojm2SRIzzkb/FunTksAhVLqaDqgkPpNAN3NvXoi6Oho/QIkq0425xj5/owWFYKVintkhx/yUxssq0WnZW6Mslr/0e8a4EwMAyff7HX+PntrrVISGqNcaZKf/axiuWYJ9vtfJP3sMCnpsL4+xJ4DsOiE3vj4tEvp0f6caa9BBZaiJeJGWOlwGLTzwzq3ITPpw2vuBH1qhQcwkqswftbdz2VDC08w0kNMNoCCjs0cimSdHy3hRXBUxY5ZZSNaKbYFQbx7wAXwM167fqDFjcJHRCv53HevNP8sIxqpWLX2typ9VXmsgaYJYsO0hcDTLWrFwVGGN6+/7mIbnGCfiuJihkFpWSZr9WlhmUUJoMXvpUqQUcQ010IZykQtrhDobXD0rI2Hh6YDtQCaEuMhI1NJ1+btHqSTpZYNd70Lsduizf+65+Rk1MzHH7Mhj/78Cz10mrm8zUCiA5vAeqm3wUFHv+XuqGd103y6L0XUqacQomX3lN21PtYh05x7NJ2NhRjMlrVAzRB7PWwBrkIBSOU7ygyB0UgMAxgu2TLwJW7JcupTBm+QyVMAF5Iyx5zRfikkCjKZOb6d5++yOZnDnMWr3vDPksI2ki8="
